### PR TITLE
Updated proposal to submit PR

### PR DESCRIPTION
**Pull request by georgejacobt**
Hi Will, Please do provide review comments.

Thank You

### CODE REVIEW

**Comment by iAmWillShepherd** [comment]
There is no proposal here. Here's what I see 👇 

screen shot 2018-06-18 at 7 30 55 pm

**Comment by georgejacobt** [comment]
Hi Will, Yep, it sure looks like its getting minimized.....but was able to maximize and get it shown by pushing on the little buttons...is that what you are referring to..?

**Comment by iAmWillShepherd** [comment]
The file isn't minimized, its just that this branch only has those changes as seen by the diff.

**Comment by georgejacobt** [comment]
thats what it is! we unwittingly had merged the first PR and this one had only a few changes. I could merge a blank branch and submit a new PR so you can see it completely....should I just do that ? let me know..sorry for the back and forth..

**Comment by georgejacobt** [comment]
Closing this PR and have opened another one that shows the full file.

**Pull request closed without merging**
